// API Keys configuration
export const API_KEYS = {
  UNSPLASH_ACCESS_KEY: process.env.EXPO_PUBLIC_UNSPLASH_ACCESS_KEY || '',
  UNSPLASH_SECRET_KEY: process.env.EXPO_PUBLIC_UNSPLASH_SECRET_KEY || '',
  GOOGLE_CUSTOM_SEARCH_API_KEY: process.env.EXPO_PUBLIC_GOOGLE_CUSTOM_SEARCH_API_KEY || '',
  GOOGLE_CUSTOM_SEARCH_ENGINE_ID: process.env.EXPO_PUBLIC_GOOGLE_CUSTOM_SEARCH_ENGINE_ID || '',
}; 